# Generated by Django 5.1.7 on 2025-03-13 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_logbook_remark_increment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='increment',
            old_name='duty_status',
            new_name='dutyStatus',
        ),
        migrations.AlterField(
            model_name='increment',
            name='logbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='api.logbook'),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
