# Generated by Django 5.1.7 on 2025-03-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_duty_status_increment_dutystatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fuel', 'Fuel Stop'), ('current', 'Current'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_lng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_lng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='dropoff_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_lat',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_lng',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='pickup_location',
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='trip',
            name='locations',
            field=models.ManyToManyField(related_name='trips', to='api.location'),
        ),
    ]
