# Generated by Django 5.1.7 on 2025-03-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_trip_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
