# Generated by Django 5.1.7 on 2025-03-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_location_distance_location_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to='api.trip'),
        ),
    ]
